function channelIdx = selectChannelWindow(numChannels)
% Select Channel Window ---------------------------------------------------
% David S. White
% 2021-09-14

% Popup window to select channels to load when running loadVideo.
% Adapted from https://www.mathworks.com/matlabcentral/answers/502990-create-a-input-dialog-with-text-entry-and-also-drop-down-menu

% Output
% channelIdx = [2,1]. Integer index of channel 1 and channel 2.

% -------------------------------------------------------------------------


% launch app in center with specified size
appWidth = 200;  % pixels
appHeight = 100;
screenSize = get(0,'ScreenSize'); % in pixels
centerX = round(screenSize(3)/2 - appWidth/2);
centerY = round(screenSize(4)/2 - appHeight/2);
selectChannelApp = figure('CloseRequestFcn',@close_req_fun,'menu','none',...
    'Name', 'Select Channel', 'NumberTitle','off','MenuBar','None',...
    'units','pixels', 'Position',[centerX,centerY,appWidth,appHeight],...
    'Resize','off');

% channel list
if numChannels == 2
    channelOptions = {'Detector 1', 'Detector 2', 'None'};
else
    channelOptions = {'GG', 'GR', 'RG', 'RR', 'None'};
end

channelText1 = uicontrol(selectChannelApp,...
    'Style','text',...
    'units','normalized',...
    'Position',[0.05 0.5 0.5 0.4],...
    'String','Channel 1',...
    'HorizontalAlignment','left',...
    'FontName','Helvetica',...
    'FontSize',12);

dropDown1=uicontrol('Style', 'popupmenu',....
    'String', channelOptions, ...
    'Parent',selectChannelApp,...
    'Units','Normalized', ...
    'Position', [.4, .5, .5, 0.4]);

channelText2 = uicontrol(selectChannelApp,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.2 0.5 0.4],...
    'String','Channel 2',...
    'HorizontalAlignment','left',...
    'FontName','Helvetica',...
    'FontSize',12);

dropDown2=uicontrol('Style', 'popupmenu',...
    'String', channelOptions, ...
    'Parent',selectChannelApp,...
    'Units','Normalized', ...
    'Position', [.4, .2, .5, 0.4]);

button_select = uicontrol(selectChannelApp,...
    'Style','pushbutton',...
    'units','normalized',...
    'Position',[0.15 0.1 0.3 0.2],...
    'String','Ok',...
    'HorizontalAlignment','center',...
    'FontName','Helvetica',...
    'FontSize',12,...
    'Callback','close(gcbf)');

button_cancel=uicontrol('Style', 'pushbutton', 'String', 'cancel', ...
    'Style','pushbutton',...
    'units','normalized',...
    'Position',[0.55 0.1 0.3 0.2],...
    'String','Cancel',...
    'HorizontalAlignment','center',...
    'FontName','Helvetica',...
    'FontSize',12,...
    'Tag','0','Callback',@cancelfun);

uiwait(selectChannelApp)

%figure is now closing
if strcmp(button_cancel.Tag,'0')%not canceled, get actual inputs
    channelIdx = [dropDown1.Value, dropDown2.Value];
end
%actually close the figure
delete(selectChannelApp)
end

function cancelfun(h,~)
set(h,'Tag','1')
uiresume
end

function close_req_fun(~,~)
uiresume
end